volumes:
  ui:
  zed_resources:

services:
  backend:
    build:
      context: ./services/backend/
      dockerfile: ./Dockerfile
    command: ros2 launch cart_launch autonomous_launcher.launch.py #can be overriden with $BACKEND_COMMAND
    environment:
      - BACKEND_COMMAND #will override the default command above
      - ROS_DOMAIN_ID=0
      - $HOME/.ssh:/root/.ssh
      - $HOME/.gitconfig:/root/.gitconfig
      - DISPLAY
      - XDG_RUNTIME_DIR
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - /dev:/dev
      - zed_resources:/usr/local/zed/resources
      - type: bind
        source: $HOME/dev_ws
        target: /root/dev_ws
    privileged: true
    runtime: nvidia
    network_mode: "host"
  frontend:
    build:
      context: ./services/frontend/
      dockerfile: ./Dockerfile
    command: npm run dev #can be overriden with $FRONTEND_COMMAND
    environment:
      - FRONTEND_COMMAND #will override the default command above
      - $HOME/.gitconfig:/root/.gitconfig
    network_mode: "host"
    volumes:
      - $HOME/.ssh:/root/.ssh
      - ui:/ui
  anomaly_detection:
    build:
      context: ./services/anomaly_detection
      dockerfile: ./Dockerfile
    depends_on:
      - backend
    command: python3 manager.py
    environment:
      - ANOMALY_DETECTION_COMMAND # allows for default command override from entrypoint.sh
      - ROS_DOMAIN_ID=0
    volumes:
      - type: bind
        source: $HOME/dev_ws/src/OA_SECRET.txt
        target: /mnt/OA_SECRET.txt
      - type: bind
        source: $HOME/dev_ws/src
        target: /dev_ws/src
    privileged: true
    runtime: nvidia
    network_mode: "host"
    ipc: "host"
