volumes:
  ui:
  zed_resources:

services:
  backend:
    build:
      context: ./services/backend/
      dockerfile: ./Dockerfile
    command: ros2 launch cart_launch autonomous_launcher.launch.py #can be overriden with $BACKEND_COMMAND
    environment:
      - BACKEND_COMMAND #will override the default command above
      - ROS_DOMAIN_ID=0
      - $HOME/.ssh:/root/.ssh
      - $HOME/.gitconfig:/root/.gitconfig
      - DISPLAY
      - XDG_RUNTIME_DIR
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - /dev:/dev
      - zed_resources:/usr/local/zed/resources
      - type: bind
        source: $HOME/dev_ws
        target: /dev_ws
    privileged: true
    runtime: nvidia
    network_mode: "host"
  frontend:
    build:
      context: ./services/frontend/
      dockerfile: ./Dockerfile
    command: npm run dev #can be overriden with $FRONTEND_COMMAND
    environment:
      - FRONTEND_COMMAND #will override the default command above
      - $HOME/.gitconfig:/root/.gitconfig
    network_mode: "host"
    volumes:
      - $HOME/.ssh:/root/.ssh
      - ui:/ui
    ipc: "host"
  fer:
    build:
      context: ./services/fer/
      dockerfile: ./Dockerfile
    depends_on:
      - backend
    command: python3 EmotionDetection.py
    environment:
      - FER_COMMAND
      - ROS_DOMAIN_ID=0
    volumes:
      - $HOME/dev_ws/src/OA_SECRET.txt:/mnt/OA_SECRET.txt # grabbing OA_secret
      - $HOME/dev_ws:/dev_ws # think about getting specific to the repo
    privileged: true
    runtime: nvidia
    network_mode: "host"
    ipc: "host"
